name: Hello World

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "a demo build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test phase
        run: echo "running test test case"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the app
        run: echo "deplo the app"
