name: Env demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        default: prod
        
jobs:
  inputs_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Deply the Application to ${{ inputs.environment }}"
