name: Outputs Demo

on: push

jobs:
  job1: build
    outputs:
      version: ${{ steps.step1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Step one Build step
        id: step1
        run: echo"version=0.1" >> $ {{ GITHUB_OUTPUT }}
      - name: step two
        run: echo "this version is $ {{ steps.step1.outputs.version }}"

  job2: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "we are deploying the app with version $ {{ needs.build.outputs.version }}"
